"""delete path column

Revision ID: 09acf784d9f9
Revises: aa7fcd08dd72
Create Date: 2025-05-22 09:27:53.808604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09acf784d9f9'
down_revision: Union[str, None] = 'aa7fcd08dd72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_item', schema=None) as batch_op:
        batch_op.drop_column('path')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('path', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
