"""adding email and creation_date to tb_account

Revision ID: 22f3b213c8c2
Revises: 57a6c1213149
Create Date: 2025-05-17 22:00:39.736150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22f3b213c8c2'
down_revision: Union[str, None] = '57a6c1213149'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('creation_date', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_account', schema=None) as batch_op:
        batch_op.drop_column('creation_date')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
