"""changing names

Revision ID: 2a5a8a397e15
Revises: 8391fff3d154
Create Date: 2025-05-07 09:54:28.169244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a5a8a397e15'
down_revision: Union[str, None] = '8391fff3d154'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_tb_item')
    with op.batch_alter_table('tb_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('update_date', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('creation_date', sa.Float(), nullable=False))
        batch_op.drop_column('updateDate')
        batch_op.drop_column('creationDate')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('creationDate', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('updateDate', sa.INTEGER(), nullable=False))
        batch_op.drop_column('creation_date')
        batch_op.drop_column('update_date')

    op.create_table('_alembic_tmp_tb_item',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('extension', sa.VARCHAR(), nullable=False),
    sa.Column('path', sa.VARCHAR(), nullable=False),
    sa.Column('size', sa.INTEGER(), nullable=False),
    sa.Column('size_prefix', sa.VARCHAR(), nullable=False),
    sa.Column('type', sa.VARCHAR(length=6), nullable=False),
    sa.Column('data', sa.BLOB(), nullable=False),
    sa.Column('parentid', sa.INTEGER(), nullable=True),
    sa.Column('ownerid', sa.INTEGER(), nullable=True),
    sa.Column('update_date', sa.FLOAT(), nullable=False),
    sa.Column('creation_date', sa.FLOAT(), nullable=False),
    sa.ForeignKeyConstraint(['ownerid'], ['user.id'], ),
    sa.ForeignKeyConstraint(['parentid'], ['tb_item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
