"""renaming_and_cleaning_fields

Revision ID: 2b220eb1cd06
Revises: ff7423ca77a1
Create Date: 2026-01-10 16:51:08.192714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2b220eb1cd06'
down_revision: Union[str, None] = 'ff7423ca77a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_user_account',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_file',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('extension', sa.String(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('size_prefix', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('FILE', 'FOLDER', name='itemtype'), nullable=False),
    sa.Column('content_type', sa.String(), nullable=False),
    sa.Column('to_delete', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('parentid', sa.String(), nullable=True),
    sa.Column('ownerid', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['ownerid'], ['tb_user_account.id'], ),
    sa.ForeignKeyConstraint(['parentid'], ['tb_file.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('tb_item')
    op.drop_table('tb_account')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_account',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('creation_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='tb_account_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('tb_item',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('extension', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('size', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('size_prefix', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('type', postgresql.ENUM('FILE', 'FOLDER', name='itemtype'), autoincrement=False, nullable=False),
    sa.Column('content_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('update_date', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('creation_date', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('parentid', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('ownerid', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('processing_state', postgresql.ENUM('PROCESSING', 'COMPLETE', 'STABLE', name='item_processing_state'), server_default=sa.text("'COMPLETE'::item_processing_state"), autoincrement=False, nullable=False),
    sa.Column('to_delete', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['ownerid'], ['tb_account.id'], name='tb_item_ownerid_fkey'),
    sa.ForeignKeyConstraint(['parentid'], ['tb_item.id'], name='tb_item_parentid_fkey'),
    sa.PrimaryKeyConstraint('id', name='tb_item_pkey')
    )
    op.drop_table('tb_file')
    op.drop_table('tb_user_account')
    # ### end Alembic commands ###
