"""added is_dir also removed type and to_delete

Revision ID: 4f27413cb7c2
Revises: 2b220eb1cd06
Create Date: 2026-01-17 17:54:40.794793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4f27413cb7c2'
down_revision: Union[str, None] = '2b220eb1cd06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_directory', sa.Boolean(), nullable=False))
        batch_op.create_index(batch_op.f('ix_tb_file_parentid'), ['parentid'], unique=False)
        batch_op.drop_column('type')
        batch_op.drop_column('to_delete')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('to_delete', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('type', postgresql.ENUM('FILE', 'FOLDER', name='itemtype'), autoincrement=False, nullable=False))
        batch_op.drop_index(batch_op.f('ix_tb_file_parentid'))
        batch_op.drop_column('is_directory')

    # ### end Alembic commands ###
