"""removing data column tb_item

Revision ID: 57a6c1213149
Revises: ce92d6ae8dd4
Create Date: 2025-05-17 16:34:39.989090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57a6c1213149'
down_revision: Union[str, None] = 'ce92d6ae8dd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_item', schema=None) as batch_op:
        batch_op.drop_column('data')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data', sa.BLOB(), nullable=False))

    # ### end Alembic commands ###
