"""Create database

Revision ID: 8391fff3d154
Revises: 
Create Date: 2025-05-06 13:40:01.702332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8391fff3d154'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('salt', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('tb_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('extension', sa.String(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('size_prefix', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('FILE', 'FOLDER', name='itemtype'), nullable=False),
    sa.Column('data', sa.LargeBinary(), nullable=False),
    sa.Column('updateDate', sa.Integer(), nullable=False),
    sa.Column('creationDate', sa.Integer(), nullable=False),
    sa.Column('parentid', sa.Integer(), nullable=True),
    sa.Column('ownerid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ownerid'], ['user.id'], ),
    sa.ForeignKeyConstraint(['parentid'], ['tb_item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_item')
    op.drop_table('user')
    # ### end Alembic commands ###
