"""creating the processing state column

Revision ID: 887d4c31e28c
Revises: 9531e8336e75
Create Date: 2025-05-28 16:36:16.347107

"""

from typing import Sequence, Union
from app.enums.enums import ProcessingState

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "887d4c31e28c"
down_revision: Union[str, None] = "9531e8336e75"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        f"CREATE TYPE item_processing_state AS ENUM ('PROCESSING', 'COMPLETE', 'STABLE')"
    )
    op.add_column(
        "tb_item",
        sa.Column(
            "processing_state",
            sa.Enum("COMPLETE", "STABLE", name="item_processing_state"),
            server_default="COMPLETE",
            nullable=False,
        ),
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("processing_state")
    op.execute("DROP TYPE item_processing_state")

    # ### end Alembic commands ###
