"""delete bucketid column

Revision ID: a0aac7c3bc43
Revises: 09acf784d9f9
Create Date: 2025-05-22 10:15:28.101452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0aac7c3bc43'
down_revision: Union[str, None] = '09acf784d9f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_item', schema=None) as batch_op:
        batch_op.drop_column('bucketid')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bucketid', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
