"""adding content_type

Revision ID: aa7fcd08dd72
Revises: 22f3b213c8c2
Create Date: 2025-05-20 13:40:27.420617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa7fcd08dd72'
down_revision: Union[str, None] = '22f3b213c8c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content_type', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_item', schema=None) as batch_op:
        batch_op.drop_column('content_type')

    # ### end Alembic commands ###
