"""to_delete column tb_item table

Revision ID: ff7423ca77a1
Revises: 887d4c31e28c
Create Date: 2025-05-30 13:59:02.778890

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "ff7423ca77a1"
down_revision: Union[str, None] = "887d4c31e28c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tb_item", schema=None) as batch_op:
        batch_op.add_column(sa.Column("to_delete", sa.Boolean(), nullable=False))
        batch_op.alter_column(
            "processing_state",
            existing_type=postgresql.ENUM(
                "PROCESSING", "COMPLETE", "STABLE", name="item_processing_state"
            ),
            type_=sa.Enum("STABLE", "COMPLETE", name="item_processing_state"),
            existing_nullable=False,
            existing_server_default=sa.text("'COMPLETE'::item_processing_state"),
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tb_item", schema=None) as batch_op:
        batch_op.alter_column(
            "processing_state",
            existing_type=sa.Enum("STABLE", "COMPLETE", name="item_processing_state"),
            type_=postgresql.ENUM(
                "PROCESSING", "COMPLETE", "STABLE", name="item_processing_state"
            ),
            existing_nullable=False,
            existing_server_default=sa.text("'COMPLETE'::item_processing_state"),
        )
        batch_op.drop_column("to_delete")

    # ### end Alembic commands ###
