"""first_migration

Revision ID: 39dc64fce8a9
Revises: 
Create Date: 2026-01-31 20:21:07.067807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39dc64fce8a9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_user_account',
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_file',
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('extension', sa.String(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('size_prefix', sa.String(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=False),
    sa.Column('parentid', sa.String(), nullable=True),
    sa.Column('ownerid', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('is_directory', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ownerid'], ['tb_user_account.id'], ),
    sa.ForeignKeyConstraint(['parentid'], ['tb_file.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tb_file', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tb_file_parentid'), ['parentid'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_file', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tb_file_parentid'))

    op.drop_table('tb_file')
    op.drop_table('tb_user_account')
    # ### end Alembic commands ###
