name: Test

on:
  push:
    branches:
      - dev
  pull_request:
     branches:
      - dev
    

jobs:
  test-and-merge:
    runs-on: ubuntu-latest
  
    env:
      ORIGINS: "${{ secrets.ORIGINS }}"
      DATABASE_PASSWORD: "${{ secrets.DATABASE_PASSWORD }}"
      DATABASE_URL: "${{ secrets.DATABASE_URL }}"
      SUPABASE_URL: "${{ secrets.SUPABASE_URL }}"
      SUPABASE_KEY: "${{ secrets.SUPABASE_KEY }}"
      SUPABASE_JWT_SECRET: "${{ secrets.SUPABASE_JWT_SECRET }}"
      STORAGE_BUCKET_ID: "${{ secrets.STORAGE_BUCKET_ID }}"
      MODE: ${{ secrets.MODE }}
      
      
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' 
          
      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest tests
